name: build

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  alpine:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        OS_VARIANT: [3.8]
        TOOL_VARIANT: [curl, curl-iptables, git, git-ssh, iptables]
        include:
        - OS_VARIANT: 3.8
          TAG_TOOL: true
        - OS_VARIANT: 3.8
          TOOL_VARIANT: git-ssh
          TAG_LATEST: true
    env:
      IMAGE_NAME: alpine
      OS_VARIANT: ${{ matrix.OS_VARIANT }}
      TOOL_VARIANT: ${{ matrix.TOOL_VARIANT }}
      TAG_TOOL: ${{ matrix.TAG_TOOL }}
      TAG_LATEST: ${{ matrix.TAG_LATEST }}
      BASE_REGISTRY_NAMESPACE: library
      BASE_TAG_FULL: ${{ matrix.OS_VARIANT }}
      BUILD_REGISTRY_NAMESPACE: joeltimothyoh
      BUILD_TAG_FULL: ${{ matrix.OS_VARIANT }}-${{ matrix.TOOL_VARIANT }}
      BUILD_CONTEXT: variants/${{ matrix.TOOL_VARIANT }}
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (linux)
      run: |
        set -e
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
    - name: Login to docker registry
      run: echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin
      env:
        DOCKERHUB_REGISTRY_USER: joeltimothyoh
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    - name: Build image
      run: |
        set -e
        echo "IMAGE_NAME: $IMAGE_NAME"
        echo "OS_VARIANT: $OS_VARIANT"
        echo "TOOL_VARIANT: $TOOL_VARIANT"
        echo "TAG_TOOL: $TAG_TOOL"
        echo "TAG_LATEST: $TAG_LATEST"
        echo "BASE_REGISTRY_NAMESPACE: $BASE_REGISTRY_NAMESPACE"
        echo "BASE_TAG_FULL: $BASE_TAG_FULL"
        echo "BUILD_REGISTRY_NAMESPACE: $BUILD_REGISTRY_NAMESPACE"
        echo "BUILD_TAG_FULL: $BUILD_TAG_FULL"
        echo "BUILD_CONTEXT: $BUILD_CONTEXT"
        echo "BASE_IMAGE: ${BASE_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BASE_TAG_FULL}"
        echo "BUILD_IMAGE: ${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}"
        time docker pull "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}" || true
        time docker build \
            --cache-from "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}" \
            -t "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}" \
            --build-arg BASE_IMAGE="${BASE_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BASE_TAG_FULL}" \
            "$BUILD_CONTEXT"
        if [ "${TAG_TOOL}" = 'true' ]; then
            docker tag "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}" "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${TOOL_VARIANT}"
        fi
        if [ "${TAG_LATEST}" = 'true' ]; then
            docker tag "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}" "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:latest"
        fi
        docker images
        docker inspect "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${BUILD_TAG_FULL}"
    - name: Push image
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker push "${BUILD_REGISTRY_NAMESPACE}/${IMAGE_NAME}"
    - name: Clean-up
      run: docker logout
      if: always()
