name: test-githubactions

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:

  actions:
    needs: []
    runs-on: ubuntu-16.04
    steps:
    - name: action-test1
      id: test1
      uses: joeltimothyoh/action-test@master
      with:
        your-first-name: j
        your-middle-name: t
        your-last-name: o
    - name: Get easter egg
      run: |
        echo "${{ steps.test1.outputs.easter-egg }}"
