name: test-githubactions

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:

  test-powershell-6_0-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:6.0.4-ubuntu-16.04-git
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-6_1-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:6.1.3-ubuntu-18.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-6_2-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:6.2.4-ubuntu-18.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-7_0-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.0.3-ubuntu-18.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-7_1-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.1.5-ubuntu-20.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-7_2-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.2-ubuntu-22.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-7_3-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.3-ubuntu-22.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"

  test-powershell-7_4-container:
    runs-on: ubuntu-latest
    container:
      image: theohbrothers/docker-powershell:7.4-ubuntu-22.04-git
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: |
        apt-get update && apt-get install -y wget
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6'
    - name: Powershell version
      run: |
        pwsh -NoLogo -NonInteractive -NoProfile -Command '$PSVersionTable'
    - name: Ignore git permissions
      run: |
        git config --global --add safe.directory "$( pwd )"
