name: CI

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: 
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (ubuntu)
      shell: bash
      run: |
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
