name: CI

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build:
    name:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        BASE_IMAGE_REPOSITORY: [alpine]
        BASE_IMAGE_TAG: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (ubuntu)
      run: |
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
    - name: Login to docker registry
      run: echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin
      env:
        DOCKERHUB_REGISTRY_USER: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    - name: Build image
      run: |
        echo "BASE_IMAGE_REPOSITORY: $BASE_IMAGE_REPOSITORY"
        echo "BASE_IMAGE_TAG: $BASE_IMAGE_TAG"
        BASE_IMAGE="${BASE_IMAGE_REPOSITORY}:${BASE_IMAGE_TAG}"
        echo "BASE_IMAGE: $BASE_IMAGE"
        docker pull "$BASE_IMAGE"
      env:
        BASE_IMAGE_REPOSITORY: ${{ matrix.BASE_IMAGE_REPOSITORY }}
        BASE_IMAGE_TAG: ${{ matrix.BASE_IMAGE_TAG }}
    - name: List images
      run: docker images
    - name: Clean-up
      run: docker logout
      if: always()
