name: CI

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build:
    name:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        BASE_IMAGE_REPO: [alpine]
        BASE_IMAGE_TAG: [3.8, 3.9]
        BUILD_IMAGE_VARIANT: [curl, curl-iptables, git, git-ssh, iptables]
        include:
          - BUILD_IMAGE_VARIANT: git-ssh
            LATEST: true
    steps:
    - uses: actions/checkout@v1
    - name: Display system info (ubuntu)
      run: |
        hostname
        whoami
        cat /etc/*release
        lscpu
        free
        df -h
        pwd
        docker info
        docker version
    - name: Login to docker registry
      run: echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin
      env:
        DOCKERHUB_REGISTRY_USER: ${{ secrets.DOCKERHUB_REGISTRY_USER }}
        DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}
    - name: Build image
      run: |
        echo "BASE_IMAGE_REPO: $BASE_IMAGE_REPO"
        echo "BASE_IMAGE_TAG: $BASE_IMAGE_TAG"
        BASE_IMAGE="${BASE_IMAGE_REPO}:${BASE_IMAGE_TAG}"
        echo "BASE_IMAGE: $BASE_IMAGE"

        echo "BUILD_IMAGE_REPO: $BUILD_IMAGE_REPO"
        echo "BUILD_IMAGE_VARIANT: $BUILD_IMAGE_VARIANT"
        echo "LATEST: $LATEST"
        BUILD_IMAGE="${BUILD_IMAGE_REPO}:${BUILD_IMAGE_VARIANT}"
        echo "BUILD_IMAGE: $BUILD_IMAGE"

        time docker pull "$BUILD_IMAGE" || true
        time docker build \
          -t "$BUILD_IMAGE" \
          --cache-from "$BUILD_IMAGE" \
          --build-arg BASE_IMAGE="${BASE_IMAGE}" \
          "$BUILD_CONTEXT"
        if [ "${LATEST}" = 'true' ]; then
          docker tag "$BUILD_IMAGE" "${BUILD_IMAGE_REPO}:latest";
        fi
        docker images
      env:
        BASE_IMAGE_REPO: ${{ matrix.BASE_IMAGE_REPO }}
        BASE_IMAGE_TAG: ${{ matrix.BASE_IMAGE_TAG }}
        BUILD_IMAGE_REPO: myexampleuser/example1
        BUILD_IMAGE_VARIANT: ${{ matrix.BUILD_IMAGE_VARIANT }}
        BUILD_CONTEXT: variants/${{ matrix.BUILD_IMAGE_VARIANT }}
        LATEST: variants/${{ matrix.include.LATEST }}
    - name: Clean-up
      run: docker logout
      if: always()
